#services:
#  app:
#    image: 'num/docker'
#    build:
#      context: .
#    container_name: app
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/numbers
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=8893960
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#
#  db:
#    image: 'postgres'
#    container_name: db
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=8893960

version: '3.7'

services:

  app:
    container_name: numbers
    build: .
    ports:
      - 8080:8080
    command: java -jar --spring.profiles.active=numbersAPI-0.0.1-SNAPSHOT.jar
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/numbers
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 8893960
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    links:
      - db

  db:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 8893960
      POSTGRES_DB: numbers